# Generated by Django 3.2.16 on 2022-11-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreiRui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(blank=True, max_length=511, verbose_name='Título (página)'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title_de',
            field=models.CharField(blank=True, max_length=511, null=True, verbose_name='Título (página)'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title_en',
            field=models.CharField(blank=True, max_length=511, null=True, verbose_name='Título (página)'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title_pt',
            field=models.CharField(blank=True, max_length=511, null=True, verbose_name='Título (página)'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title_pt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título'),
        ),
    ]
