# Generated by Django 3.2.10 on 2022-01-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreiRui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='galleries',
            field=models.ManyToManyField(blank=True, to='FreiRui.Gallery'),
        ),
    ]
