# Generated by Django 3.2.16 on 2022-11-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreiRui', '0002_auto_20221104_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
