# Generated by Django 3.2.10 on 2022-02-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreiRui', '0004_auto_20220201_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Ocultado?'),
        ),
    ]
