# Generated by Django 3.2.10 on 2022-02-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreiRui', '0006_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='short_name',
            field=models.CharField(
                max_length=30, verbose_name='Nome curto (singular)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='order',
            field=models.IntegerField(
                default=0, verbose_name='Ordem da categoria na listagem'),
        ),
    ]
