# Generated by Django 3.2.10 on 2022-02-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreiRui', '0007_auto_20220202_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='title',
            field=models.CharField(
                max_length=30, verbose_name='Título (página)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(
                max_length=30, verbose_name='Nome (barra de ferramentas)'),
        ),
    ]
