# Generated by Django 3.2.10 on 2022-02-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreiRui', '0008_auto_20220202_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título (página)'),
        ),
    ]
