# Generated by Django 3.2.10 on 2022-02-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreiRui', '0009_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='facebook_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='instagram_posted',
            field=models.BooleanField(default=False),
        ),
    ]
