# Generated by Django 3.2.10 on 2022-03-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreiRui', '0012_auto_20220305_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Título (página)'),
        ),
    ]
