# Generated by Django 3.2.10 on 2022-03-10 02:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FreiRui', '0013_auto_20220307_0002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posts',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='gallery',
            new_name='Galleries',
        ),
    ]
