# Generated by Django 3.2.10 on 2022-03-13 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FreiRui', '0014_auto_20220310_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='Galleries',
            new_name='gallery',
        ),
    ]
