# Generated by Django 4.0.3 on 2022-03-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreiRui', '0015_rename_galleries_images_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='name_de',
            field=models.CharField(
                max_length=30, null=True, verbose_name='Nome (barra de ferramentas)'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_en',
            field=models.CharField(
                max_length=30, null=True, verbose_name='Nome (barra de ferramentas)'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_pt',
            field=models.CharField(
                max_length=30, null=True, verbose_name='Nome (barra de ferramentas)'),
        ),
        migrations.AddField(
            model_name='categories',
            name='short_name_de',
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name='Nome curto (singular)'),
        ),
        migrations.AddField(
            model_name='categories',
            name='short_name_en',
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name='Nome curto (singular)'),
        ),
        migrations.AddField(
            model_name='categories',
            name='short_name_pt',
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name='Nome curto (singular)'),
        ),
        migrations.AddField(
            model_name='categories',
            name='title_de',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='Título (página)'),
        ),
        migrations.AddField(
            model_name='categories',
            name='title_en',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='Título (página)'),
        ),
        migrations.AddField(
            model_name='categories',
            name='title_pt',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='Título (página)'),
        ),
        migrations.AddField(
            model_name='categories',
            name='video_url_de',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='ID do canal do YouTube'),
        ),
        migrations.AddField(
            model_name='categories',
            name='video_url_en',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='ID do canal do YouTube'),
        ),
        migrations.AddField(
            model_name='categories',
            name='video_url_pt',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='ID do canal do YouTube'),
        ),
        migrations.AddField(
            model_name='posts',
            name='text_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='text_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='title_de',
            field=models.CharField(
                max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='posts',
            name='title_en',
            field=models.CharField(
                max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='posts',
            name='title_pt',
            field=models.CharField(
                max_length=200, null=True, verbose_name='Título'),
        ),
    ]
