# Generated by Django 4.0.3 on 2022-03-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreiRui', '0016_categories_name_de_categories_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='published_de',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
        migrations.AddField(
            model_name='categories',
            name='published_en',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
        migrations.AddField(
            model_name='categories',
            name='published_pt',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
        migrations.AddField(
            model_name='posts',
            name='is_deleted_de',
            field=models.BooleanField(default=False, verbose_name='Ocultado?'),
        ),
        migrations.AddField(
            model_name='posts',
            name='is_deleted_en',
            field=models.BooleanField(default=False, verbose_name='Ocultado?'),
        ),
        migrations.AddField(
            model_name='posts',
            name='is_deleted_pt',
            field=models.BooleanField(default=False, verbose_name='Ocultado?'),
        ),
    ]
