# Generated by Django 4.0.3 on 2022-03-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreiRui', '0017_categories_published_de_categories_published_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(
                db_index=True, max_length=60, unique=True, verbose_name='Nome (barra de ferramentas)'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name_de',
            field=models.CharField(db_index=True, max_length=60, null=True,
                                   unique=True, verbose_name='Nome (barra de ferramentas)'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name_en',
            field=models.CharField(db_index=True, max_length=60, null=True,
                                   unique=True, verbose_name='Nome (barra de ferramentas)'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name_pt',
            field=models.CharField(db_index=True, max_length=60, null=True,
                                   unique=True, verbose_name='Nome (barra de ferramentas)'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='order',
            field=models.IntegerField(
                db_index=True, default=0, verbose_name='Ordem da categoria na listagem'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='published',
            field=models.BooleanField(
                db_index=True, default=True, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='published_de',
            field=models.BooleanField(
                db_index=True, default=True, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='published_en',
            field=models.BooleanField(
                db_index=True, default=True, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='published_pt',
            field=models.BooleanField(
                db_index=True, default=True, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='is_deleted',
            field=models.BooleanField(
                db_index=True, default=False, verbose_name='Ocultado?'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='is_deleted_de',
            field=models.BooleanField(
                db_index=True, default=False, verbose_name='Ocultado?'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='is_deleted_en',
            field=models.BooleanField(
                db_index=True, default=False, verbose_name='Ocultado?'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='is_deleted_pt',
            field=models.BooleanField(
                db_index=True, default=False, verbose_name='Ocultado?'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='published_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True,
                                       verbose_name='Data de publicação (selecione no futuro para agendar)'),
        ),
    ]
