# Generated by Django 4.0.3 on 2022-04-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreiRui', '0018_alter_categories_name_alter_categories_name_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(
                max_length=60, unique=True, verbose_name='Nome (barra de ferramentas)'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name_de',
            field=models.CharField(
                max_length=60, null=True, unique=True, verbose_name='Nome (barra de ferramentas)'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name_en',
            field=models.CharField(
                max_length=60, null=True, unique=True, verbose_name='Nome (barra de ferramentas)'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name_pt',
            field=models.CharField(
                max_length=60, null=True, unique=True, verbose_name='Nome (barra de ferramentas)'),
        ),
    ]
