# Generated by Django 4.0.3 on 2022-04-12 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FreiRui', '0020_alter_categories_name_alter_categories_name_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='name_pt',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='published_de',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='published_en',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='published_pt',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='short_name_de',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='short_name_en',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='short_name_pt',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='title_pt',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='video_url_de',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='video_url_en',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='video_url_pt',
        ),
        migrations.AddField(
            model_name='posts',
            name='category_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='FreiRui.categories', verbose_name='Categoria da postagem'),
        ),
        migrations.AddField(
            model_name='posts',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='FreiRui.categories', verbose_name='Categoria da postagem'),
        ),
        migrations.AddField(
            model_name='posts',
            name='category_pt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='FreiRui.categories', verbose_name='Categoria da postagem'),
        ),
    ]
