# Generated by Django 4.0.3 on 2022-04-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreiRui', '0021_remove_categories_name_de_remove_categories_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='category_de',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='category_pt',
        ),
        migrations.AddField(
            model_name='categories',
            name='name_de',
            field=models.CharField(db_index=True, max_length=60, null=True,
                                   unique=True, verbose_name='Nome (barra de ferramentas)'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_en',
            field=models.CharField(db_index=True, max_length=60, null=True,
                                   unique=True, verbose_name='Nome (barra de ferramentas)'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_pt',
            field=models.CharField(db_index=True, max_length=60, null=True,
                                   unique=True, verbose_name='Nome (barra de ferramentas)'),
        ),
        migrations.AddField(
            model_name='categories',
            name='published_de',
            field=models.BooleanField(
                db_index=True, default=True, verbose_name='Publicado'),
        ),
        migrations.AddField(
            model_name='categories',
            name='published_en',
            field=models.BooleanField(
                db_index=True, default=True, verbose_name='Publicado'),
        ),
        migrations.AddField(
            model_name='categories',
            name='published_pt',
            field=models.BooleanField(
                db_index=True, default=True, verbose_name='Publicado'),
        ),
        migrations.AddField(
            model_name='categories',
            name='short_name_de',
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name='Nome curto (singular)'),
        ),
        migrations.AddField(
            model_name='categories',
            name='short_name_en',
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name='Nome curto (singular)'),
        ),
        migrations.AddField(
            model_name='categories',
            name='short_name_pt',
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name='Nome curto (singular)'),
        ),
        migrations.AddField(
            model_name='categories',
            name='title_de',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='Título (página)'),
        ),
        migrations.AddField(
            model_name='categories',
            name='title_en',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='Título (página)'),
        ),
        migrations.AddField(
            model_name='categories',
            name='title_pt',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='Título (página)'),
        ),
        migrations.AddField(
            model_name='categories',
            name='video_url_de',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='ID do canal do YouTube'),
        ),
        migrations.AddField(
            model_name='categories',
            name='video_url_en',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='ID do canal do YouTube'),
        ),
        migrations.AddField(
            model_name='categories',
            name='video_url_pt',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='ID do canal do YouTube'),
        ),
    ]
