# Generated by Django 4.0.3 on 2022-04-12 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FreiRui', '0022_remove_posts_category_de_remove_posts_category_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='published_de',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='published_en',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='published_pt',
        ),
    ]
