# Generated by Django 4.0.3 on 2022-06-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreiRui', '0023_remove_categories_published_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='published_de',
            field=models.BooleanField(
                db_index=True, default=True, verbose_name='Publicado'),
        ),
        migrations.AddField(
            model_name='categories',
            name='published_en',
            field=models.BooleanField(
                db_index=True, default=True, verbose_name='Publicado'),
        ),
        migrations.AddField(
            model_name='categories',
            name='published_pt',
            field=models.BooleanField(
                db_index=True, default=True, verbose_name='Publicado'),
        ),
    ]
